# Generated by Django 5.0.14 on 2025-04-23 17:27
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_updated'),
    ]

    operations = [
        TrigramExtension()
    ]
